// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr9n2VnQ_N1a_83bxl0p2cYjxx614JTeQ',
    appId: '1:967661813907:web:b20312a8e90aef9815cd66',
    messagingSenderId: '967661813907',
    projectId: 'info-manager-se',
    authDomain: 'info-manager-se.firebaseapp.com',
    storageBucket: 'info-manager-se.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO-YkJLRXCHhd5sTaF0DCGMWbba1r7cnQ',
    appId: '1:967661813907:android:d54f2f49f244736415cd66',
    messagingSenderId: '967661813907',
    projectId: 'info-manager-se',
    storageBucket: 'info-manager-se.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz9HvaFQa5Fbi9y-vzLmhUqdYCHhpNmKk',
    appId: '1:967661813907:ios:3b1242fb0f46b84415cd66',
    messagingSenderId: '967661813907',
    projectId: 'info-manager-se',
    storageBucket: 'info-manager-se.firebasestorage.app',
    iosBundleId: 'com.example.infoManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz9HvaFQa5Fbi9y-vzLmhUqdYCHhpNmKk',
    appId: '1:967661813907:ios:3b1242fb0f46b84415cd66',
    messagingSenderId: '967661813907',
    projectId: 'info-manager-se',
    storageBucket: 'info-manager-se.firebasestorage.app',
    iosBundleId: 'com.example.infoManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDr9n2VnQ_N1a_83bxl0p2cYjxx614JTeQ',
    appId: '1:967661813907:web:13a927936e4ec1a615cd66',
    messagingSenderId: '967661813907',
    projectId: 'info-manager-se',
    authDomain: 'info-manager-se.firebaseapp.com',
    storageBucket: 'info-manager-se.firebasestorage.app',
  );
}
