import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'services/firestore_service.dart';
import 'screens/home_page.dart';
import 'firebase_options.dart'; // generated by flutterfire configure

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // debug prints to help diagnose web vs native and projectId
  debugPrint('kIsWeb: $kIsWeb');
  final opts = DefaultFirebaseOptions.currentPlatform;
  debugPrint('FirebaseOptions projectId: ${opts.projectId}');

  final service = FirestoreService();
  runApp(MyApp(service: service));
}

class MyApp extends StatelessWidget {
  final FirestoreService service;
  const MyApp({super.key, required this.service});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Information Manager',
      debugShowCheckedModeBanner: false, // remove debug tag
      theme: ThemeData(
        primarySwatch: Colors.indigo,
        scaffoldBackgroundColor: Colors.white,
      ),
      home: HomePage(service: service),
    );
  }
}
